services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: imo_db
      POSTGRES_USER: imo_user
      POSTGRES_PASSWORD: imo_pass
    ports:
      - "5433:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
